# Generated by Django 3.1.7 on 2021-04-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuemSomos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valores', models.TextField(blank=True, verbose_name='Valores')),
                ('missao', models.TextField(blank=True, verbose_name='Missão')),
                ('visao', models.TextField(blank=True, verbose_name='Visão')),
            ],
        ),
    ]
