# Generated by Django 3.1.7 on 2021-04-23 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesParceiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(blank=True, max_length=50, verbose_name='Nome')),
                ('image_Parceiro', models.ImageField(blank=True, upload_to='imagens/', verbose_name='Imagem do parceiro')),
            ],
        ),
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lugar', models.CharField(max_length=50, verbose_name='Nome do lugar')),
                ('image_portifolio', models.ImageField(blank=True, upload_to='imagens/', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_servico', models.ImageField(blank=True, upload_to='imagens/', verbose_name='Imagem do serviço')),
                ('nome_servico', models.CharField(max_length=50, verbose_name='Nome')),
                ('descricao_servico', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.RenameModel(
            old_name='QuemSomos',
            new_name='Sobre',
        ),
        migrations.CreateModel(
            name='BlogIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_blogindex', models.CharField(blank=True, max_length=50, verbose_name='Descrição')),
                ('image_blogindex', models.ImageField(blank=True, upload_to='imagens/', verbose_name='Imagem')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa')),
            ],
        ),
    ]
