# Generated by Django 3.1.7 on 2021-04-23 19:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('aplicacao', '0002_auto_20210423_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, verbose_name='Titulo da postagem')),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data da Postagem')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa')),
            ],
        ),
    ]
