# Generated by Django 3.1.7 on 2021-04-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descricao_post',
            field=models.TextField(blank=True, verbose_name='Texto'),
        ),
    ]
