# Generated by Django 3.1.7 on 2021-04-24 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('aplicacao', '0004_post_descricao_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_blog', models.CharField(blank=True, max_length=50, verbose_name='Descrição')),
                ('image_blog', models.ImageField(blank=True, upload_to='imagens/', verbose_name='Imagem')),
                ('pessoa_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa')),
            ],
        ),
        migrations.DeleteModel(
            name='Portifolio',
        ),
    ]
