# Generated by Django 3.1.7 on 2021-04-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0005_auto_20210424_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descricao_blog',
            field=models.CharField(blank=True, max_length=50, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_blog',
            field=models.ImageField(blank=True, upload_to='imagens/', verbose_name='Imagem'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
