# Generated by Django 3.1.7 on 2021-04-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0006_auto_20210424_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='foto_servico',
            field=models.FileField(blank=True, upload_to='imagens_SVG/', verbose_name='Imagem do serviço'),
        ),
    ]
